name: Build Flutter Web
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      - name: Flutter Pub Get
        run: flutter pub get
      - name: Build Web (release)
        run: flutter build web --release --web-renderer canvaskit
      - name: Zip build/web
        run: |
          cd build/web
          zip -r ../../web-dist.zip .
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web-dist.zip
