name: mokhtafoun
description: Full Mokhtafoun app (Flutter + Firebase + PWA + Functions AI)
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.9
  firebase_analytics: ^10.8.9
  provider: ^6.1.2
  share_plus: ^10.0.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  record: ^5.2.0
  geolocator: ^13.0.1
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
